version: '3'
services:
  backend:
    env_file:
      - backend.env
    build:
      dockerfile: Dockerfile
      context: .
    # entrypoint: []
    links:
      - db
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "80:8000"
    volumes:
      - ./:/app
      - ~/.covid_bash_history:/home/root/.bash_history
    environment:
      - HISTFILE=/home/root/.bash_history

  db:
    restart: always
    ports:
      - "5432:5432"
    image: postgres:11
    env_file:
      - db.env
    volumes:
      - local-db:/var/lib/postgresql/data

volumes:
  local-db:
